# Generated by Django 5.1.1 on 2024-09-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlybudget',
            name='label',
            field=models.CharField(default='', max_length=255),
        ),
    ]
